# Generated by Django 5.2.5 on 2025-08-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
